spring:
  application:
    name: midday-meal-backend
  
  datasource:
    url: ${DATABASE_URL:${DATABASE_PUBLIC_URL:jdbc:postgresql://localhost:5432/middaymeal_db}}
    username: ${POSTGRES_USER:${DB_USERNAME:middaymeal_user}}
    password: ${POSTGRES_PASSWORD:${DB_PASSWORD:password}}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    jwt:
      secret-key: ${JWT_SECRET:mySecretKey}
      expiration: 86400000 # 24 hours
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.middaymeal: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/midday-meal.log

# Custom application properties
app:
  upload:
    dir: uploads/
  supported:
    languages: en,mr
  default:
    language: en